-- marketplace-streaming: RisingWave source definitions — FAULT INJECTION MODE
--
-- This file is the fault-injection variant of 01_sources.sql.
-- The only difference: all WATERMARK intervals are '6 hours' instead of '5 minutes'.
--
-- A 6-hour watermark means RisingWave waits up to 6 real hours (at 1x speed,
-- or 6 sim-hours at demo acceleration) before closing a window, tolerating
-- late_arrival faults where event_time is rewound by up to
-- late_arrival_max_delay_seconds (default 300s, configurable up to 6h).
--
-- DO NOT edit this file for watermark changes — edit both this file AND
-- 01_sources.sql, then open a PR. The two files are the authoritative,
-- independently reviewable record of the two modes.
--
-- Switch between modes via:
--   make fault-demo       (activates fault mode, runs demo, restores standard)
--   scripts/switch_watermark.py --mode fault
--   scripts/switch_watermark.py --mode standard
--
-- See docs/adr/0002-architecture.md § "Watermark Decision" for rationale.
-- See docs/adr/0004-ci-strategy.md § "Watermark mode switch" for the two-file pattern.

CREATE SOURCE IF NOT EXISTS order_placed_source (
    event_id             VARCHAR,
    event_type           VARCHAR,
    event_version        VARCHAR,
    produced_at          TIMESTAMPTZ,
    event_time           TIMESTAMPTZ,
    is_injected_fault    BOOLEAN,
    fault_type           VARCHAR,
    order_id             VARCHAR,
    customer_id          VARCHAR,
    seller_id            VARCHAR,
    product_category     VARCHAR,
    payment_type         VARCHAR,
    order_item_count     INT,
    freight_value_brl    DECIMAL,
    payment_value_brl    DECIMAL,
    sla_deadline_at      TIMESTAMPTZ,
    state_code           VARCHAR,
    city                 VARCHAR,
    WATERMARK FOR event_time AS event_time - INTERVAL '6 hours'
)
WITH (
    connector = 'kafka',
    topic = 'order_placed',
    properties.bootstrap.server = 'redpanda:9092',
    scan.startup.mode = 'earliest'
)
FORMAT PLAIN ENCODE JSON;

CREATE SOURCE IF NOT EXISTS shipment_created_source (
    event_id               VARCHAR,
    event_type             VARCHAR,
    event_version          VARCHAR,
    produced_at            TIMESTAMPTZ,
    event_time             TIMESTAMPTZ,
    is_injected_fault      BOOLEAN,
    fault_type             VARCHAR,
    shipment_id            VARCHAR,
    order_id               VARCHAR,
    seller_id              VARCHAR,
    carrier_code           VARCHAR,
    estimated_delivery_at  TIMESTAMPTZ,
    actual_pickup_at       TIMESTAMPTZ,
    days_to_pickup         INT,
    WATERMARK FOR event_time AS event_time - INTERVAL '6 hours'
)
WITH (
    connector = 'kafka',
    topic = 'shipment_created',
    properties.bootstrap.server = 'redpanda:9092',
    scan.startup.mode = 'earliest'
)
FORMAT PLAIN ENCODE JSON;

CREATE SOURCE IF NOT EXISTS delivery_update_source (
    event_id           VARCHAR,
    event_type         VARCHAR,
    event_version      VARCHAR,
    produced_at        TIMESTAMPTZ,
    event_time         TIMESTAMPTZ,
    scanned_at         TIMESTAMPTZ,
    is_injected_fault  BOOLEAN,
    fault_type         VARCHAR,
    update_id          VARCHAR,
    shipment_id        VARCHAR,
    order_id           VARCHAR,
    status             VARCHAR,
    location_state     VARCHAR,
    delivery_zone      VARCHAR,
    sequence_number    INT,
    is_final           BOOLEAN,
    WATERMARK FOR scanned_at AS scanned_at - INTERVAL '6 hours'
)
WITH (
    connector = 'kafka',
    topic = 'delivery_update',
    properties.bootstrap.server = 'redpanda:9092',
    scan.startup.mode = 'earliest'
)
FORMAT PLAIN ENCODE JSON;

CREATE SOURCE IF NOT EXISTS seller_activity_source (
    event_id           VARCHAR,
    event_type         VARCHAR,
    event_version      VARCHAR,
    produced_at        TIMESTAMPTZ,
    event_time         TIMESTAMPTZ,
    is_injected_fault  BOOLEAN,
    fault_type         VARCHAR,
    activity_id        VARCHAR,
    seller_id          VARCHAR,
    activity_type      VARCHAR,
    review_score       FLOAT,
    product_category   VARCHAR,
    state_code         VARCHAR,
    WATERMARK FOR event_time AS event_time - INTERVAL '6 hours'
)
WITH (
    connector = 'kafka',
    topic = 'seller_activity',
    properties.bootstrap.server = 'redpanda:9092',
    scan.startup.mode = 'earliest'
)
FORMAT PLAIN ENCODE JSON;
